name: TestWorkflow

on:
  issue_comment

  
jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Fetch All
      run: git fetch --prune --unshallow
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm ci
      env:
        CI: true
    - name: Get Package Version
      uses: ./.github/actions/get-version
      id: package
    - name: Bump Version and Generate Changelog
      id: version
      uses: ci010/conventional-changelog-action@master
      with:
        github-token: ${{ secrets.github_token }}
        version: ${{ steps.package.outputs.version }}
        tag-prefix: 'v'
    - name: Update package.json and CHANGELOG.md
      uses: ./.github/actions/update-version-changelog
      with:
        version: ${{ steps.version.outputs.version }}
        changelog: ${{ steps.version.outputs.changelog }}
    - name: Create Pull Request
      if: ${{ steps.version.outputs.skipped == 'false' }}
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: >-
          ${{ format('chore(release): {0}', steps.version.outputs.version) }}
        title: ${{ format('Prepare Release {0}', steps.version.outputs.version) }}
        body: ${{ steps.version.outputs.clean_changelog }}
        branch: prepare-release